baseURL = 'https://wacodatacenter.com/'
languageCode = 'en-us'
title = 'Waco Data Center Community Information'
# theme = 'agency'

[params]
  description = "Community resources and information about the proposed data center development in rural Texas"
  author = "Waco Data Center Community Action Group"
  
  # Social links
  facebook = "https://www.facebook.com/share/g/17cFKqY3q8/?mibextid=wwXIfr"
  instagram = "your-instagram"
  
  # Contact info
  email = "plcmercenary@tuta.io"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2
    
  [[menu.main]]
    name = "Resources"
    url = "/resources/"
    weight = 3
    
  [[menu.main]]
    name = "Fast Facts"
    url = "/#facts"
    weight = 4
    
  [[menu.main]]
    name = "Events"
    url = "/#events"
    weight = 5
    
  [[menu.main]]
    name = "Take Action"
    url = "/#action"
    weight = 6
    
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 7

[outputs]
  home = ["HTML", "RSS"]
  
[permalinks]
  posts = "/posts/:slug/"
  resources = "/resources/:slug/"
